# This is a basic workflow to help you get started with Actions
name: CD - Create a new release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        tags:
            - "v*.*.*" # on every version tag will build a new android artifact.
jobs:
    build:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                  java-version: "12.x"
            - name: Setup Flutter
              uses: subosito/flutter-action@v1
              with:
                  flutter-version: "3.3.0"

            - name: Pub Get Packages
              run: flutter pub get

            - name: Build APK
              env:
                  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
                  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
                  KEY_JKS: ${{ secrets.KEY_JKS }}
              run: base64 --decode "$KEY_JKS" > android/upload-keystore.jks && flutter pub get && flutter build apk --release --dart-define=SERVER_IP_PROD=${{ secrets.SERVER_IP_PROD }} --dart-define=PORT_PROD=${{ secrets.PORT_PROD }}

            - name: Create Github Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: Careot release ${{ github.ref_name }}
                  files: |
                      build/app/outputs/apk/release/*.apk
